### ISSUE TITLE
Normalize spaces and brackets

### ISSUE THREAD

**Issue by Altusvdm** [mrdannael/genum-openapi#1]
It would be great if the normalize function also handled spaces and round brackets.

I'd be happy to submit an MR that does this, however it's as simple as changing the replacers too:
```
const replacers: Replacer[] = [
  { regExp: /[-/ ()]/g, replaceWith: "_" },
  { regExp: /[.]/g, replaceWith: "__" },
];
```

**Comment by mrdannael** [comment]
Thanks for submitting an issue. This feature should be now available in version 0.5.0 :smiley:
